// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GrasshoppersWebPage.Shared.DbModels
{
    public partial class Player
    {
        public Guid PlayerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int? JerseyNumber { get; set; }
        public string FieldPosition { get; set; }
        public DateTime? BirthDate { get; set; }
    }
}